"imageTestXY\nimage[512,500] g;\ng[[x,y]] = Z;\nint foo = X;\nint bar = Y;\nfoo -> SCREEN;bar -> SCREEN;". Unexpected error happened in source code. Stack Trace:
java.lang.NullPointerException
	at org.objectweb.asm.Item.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitFieldInsn(Unknown Source)
	at cop5556fa17.CodeGenVisitor.visitExpression_PredefinedName(CodeGenVisitor.java:444)
	at cop5556fa17.AST.Expression_PredefinedName.visit(Expression_PredefinedName.java:17)
	at cop5556fa17.CodeGenVisitor.visitDeclaration_Variable(CodeGenVisitor.java:159)
	at cop5556fa17.AST.Declaration_Variable.visit(Declaration_Variable.java:24)
	at cop5556fa17.CodeGenVisitor.visitProgram(CodeGenVisitor.java:101)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:148)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeRunNAssert(CodeGenVisitorFinalTest.java:187)
	at cop5556fa17.CodeGenVisitorFinalTest.imageTestXY(CodeGenVisitorFinalTest.java:707)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

		image7: Testing failed with input: "image7//args: <inputImageURL> <outputImageURL>\nimage[1024,1024] g; \n\nimage[1024,1024] h; \ng <- @ 0;\n file f = @ 1; \ng -> SCREEN;\nh[[r,a]] =  g[r,a];h -> SCREEN; \nh -> f;". Unexpected error happened in source code. Stack Trace:
cop5556fa17.TypeCheckVisitor$SemanticException: line 6 pos 2: Source sink is not of type source
	at cop5556fa17.TypeCheckVisitor.visitDeclaration_SourceSink(TypeCheckVisitor.java:314)
	at cop5556fa17.AST.Declaration_SourceSink.visit(Declaration_SourceSink.java:22)
	at cop5556fa17.TypeCheckVisitor.visitProgram(TypeCheckVisitor.java:62)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:143)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.image7(CodeGenVisitorFinalTest.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

		imageIO1: Testing failed with input: "imageIO1//args: <inputImageFullPath> <outputImageFullPath>\n image g; \n file f = @ 1; \ng <- @ 0;\ng -> SCREEN;\ng -> f;\nimage h;\nh <- f; \nh -> SCREEN;". Unexpected error happened in source code. Stack Trace:
cop5556fa17.TypeCheckVisitor$SemanticException: line 3 pos 2: Source sink is not of type source
	at cop5556fa17.TypeCheckVisitor.visitDeclaration_SourceSink(TypeCheckVisitor.java:314)
	at cop5556fa17.AST.Declaration_SourceSink.visit(Declaration_SourceSink.java:22)
	at cop5556fa17.TypeCheckVisitor.visitProgram(TypeCheckVisitor.java:62)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:143)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.imageIO1(CodeGenVisitorFinalTest.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

		image10: Testing failed with input: "image10//args: <imageURL>\nimage[1024,1024] g; \n\nimage[1024,1024] h; \ng <- @ 0;\ng -> SCREEN;\nh[[x,y]] =  g[x,Y-y];h -> SCREEN; \n". Unexpected error happened in source code. Stack Trace:
java.lang.NullPointerException
	at org.objectweb.asm.Item.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitFieldInsn(Unknown Source)
	at cop5556fa17.CodeGenVisitor.visitExpression_PredefinedName(CodeGenVisitor.java:448)
	at cop5556fa17.AST.Expression_PredefinedName.visit(Expression_PredefinedName.java:17)
	at cop5556fa17.CodeGenVisitor.visitExpression_Binary(CodeGenVisitor.java:168)
	at cop5556fa17.AST.Expression_Binary.visit(Expression_Binary.java:20)
	at cop5556fa17.CodeGenVisitor.visitIndex(CodeGenVisitor.java:273)
	at cop5556fa17.AST.Index.visit(Index.java:37)
	at cop5556fa17.CodeGenVisitor.visitExpression_PixelSelector(CodeGenVisitor.java:288)
	at cop5556fa17.AST.Expression_PixelSelector.visit(Expression_PixelSelector.java:28)
	at cop5556fa17.CodeGenVisitor.visitStatement_Assign(CodeGenVisitor.java:577)
	at cop5556fa17.AST.Statement_Assign.visit(Statement_Assign.java:35)
	at cop5556fa17.CodeGenVisitor.visitProgram(CodeGenVisitor.java:101)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:148)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.image10(CodeGenVisitorFinalTest.java:463)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
	
	image7: Testing failed with input: "image7//args: <inputImageURL> <outputImageURL>\nimage[1024,1024] g; \n\nimage[1024,1024] h; \ng <- @ 0;\n file f = @ 1; \ng -> SCREEN;\nh[[r,a]] =  g[r,a];h -> SCREEN; \nh -> f;". Unexpected error happened in source code. Stack Trace:
cop5556fa17.TypeCheckVisitor$SemanticException: line 6 pos 2: Source sink is not of type source
	at cop5556fa17.TypeCheckVisitor.visitDeclaration_SourceSink(TypeCheckVisitor.java:314)
	at cop5556fa17.AST.Declaration_SourceSink.visit(Declaration_SourceSink.java:22)
	at cop5556fa17.TypeCheckVisitor.visitProgram(TypeCheckVisitor.java:62)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:143)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.image7(CodeGenVisitorFinalTest.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

		imageIO1: Testing failed with input: "imageIO1//args: <inputImageFullPath> <outputImageFullPath>\n image g; \n file f = @ 1; \ng <- @ 0;\ng -> SCREEN;\ng -> f;\nimage h;\nh <- f; \nh -> SCREEN;". Unexpected error happened in source code. Stack Trace:
cop5556fa17.TypeCheckVisitor$SemanticException: line 3 pos 2: Source sink is not of type source
	at cop5556fa17.TypeCheckVisitor.visitDeclaration_SourceSink(TypeCheckVisitor.java:314)
	at cop5556fa17.AST.Declaration_SourceSink.visit(Declaration_SourceSink.java:22)
	at cop5556fa17.TypeCheckVisitor.visitProgram(TypeCheckVisitor.java:62)
	at cop5556fa17.AST.Program.visit(Program.java:25)
	at cop5556fa17.CodeGenVisitorFinalTest.genCode(CodeGenVisitorFinalTest.java:143)
	at cop5556fa17.CodeGenVisitorFinalTest.genCodeNRun(CodeGenVisitorFinalTest.java:192)
	at cop5556fa17.CodeGenVisitorFinalTest.imageIO1(CodeGenVisitorFinalTest.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
	